---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: developer-induction
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: developer-induction
    spec:
      containers:
      - name: signed-commit-check
        image: quay.io/ukhomeofficedigital/developer-induction:{{.DRONE_COMMIT_SHA}}
        ports:
          - name: http
            containerPort: 80
        resources:
          limits:
            cpu: 250m
            memory: 256Mi