---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/secure-backends: "true"
  name: developer-induction-ingress
spec:
  rules:
  - host: developer-induction.notprod.homeoffice.gov.uk
    http:
      paths:
      - backend:
          serviceName: developer-induction-service
          servicePort: https
        path: /
  tls:
  - hosts:
    - developer-induction.notprod.homeoffice.gov.uk
    - www.developer-induction.notprod.homeoffice.gov.uk
    secretName: external-tls